export const RegionIdConvertir = {
    "I" : "2",
    "II" : "3",
    "III": "4",
    "IV": "5",
    "V": "6",
    "VI": "8",
    "VII": "9",
    "VIII": "10",
    "IX": "11",
    "X": "13",
    "XI": "14",
    "XII": "15",
    "XIV": "12",
    "XV": "1",
    "RM": "7",
}